pipeline {
	agent any
	stages {
		stage('Build Servlet Project') {
			steps {
				/*For windows machine */
				bat 'mvn clean package'

				/*For Mac & Linux machine */
				// sh  'mvn clean package'
			}

			post {
				success {
					echo 'Now Archiving ....'

					archiveArtifacts artifacts: '**/*.war'
				}
			}
		}
        stage('deploy build in staging area'){
            steps{
                build job: 'deploy_pipeline_test'
            }
        }

        stage('deploy to production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'approve production deployment'
                }
            }
            build job : 'deploy_prod_pipeline'
        }
        post{
            success{
                echo 'deployment is successful and credit goes to sushil'
            }
            failure{
                echo 'deployment is failed'
            }
        }
	}
}