pipeline {
	agent any
	stages {
		stage('Build Servlet Project') {
			steps {
				/*For windows machine */
				bat 'mvn clean package'

				/*For Mac & Linux machine */
				// sh  'mvn clean package'
			}

			post {
				success {
					echo 'Now Archiving ....'

					archiveArtifacts artifacts: '**/*.war'
				}
			}
		}
        stage{
            steps{
                timeout(time : 5, unit:'DAYS'){
                    input message : 'approve the production deployment?'
                }
                build job : 'deploy_prod_pipeline'
            }
            post{
                success{
                    echo 'prod deployment is successful'
                }
                failure{
                    echo 'prod deployment is failed'
                }
            }
        }
    }
}